### PR TITLE
Rename plugin to addon

### LINKED ISSUE #40: Feature list of recommended public servers broken
There is an issue with the 'features' on the list of public servers.
https://dir.friendica.social/servers

For libranet.de and some other nodes it is only showing:
HTTPS  √
+1 more

I don't know which page is fetched from the server to generate the feature list. Here is my nodeinfo for comparison:
https://libranet.de/nodeinfo/1.0

### PR DESCRIPTION
**Pull request by MrPetovan**
Related to https://github.com/friendica/friendica/pull/4288

Fixes #40

### CODE REVIEW

**Comment by annando** [comment]
Isn't there some SQL update script?

**Comment by MrPetovan** [comment]
Not that I know of, this isn't Friendica with its fancy database versioning. Although it would be easier if there was a common Friendica library I could use as a dependency for the directory, it feels a little bit duplicated between the projects.

**Comment by annando** [comment]
So do we need some shared Friendica core or should we integrate the directory into the current core?

**Comment by tobiasd** [comment]
> So do we need some shared Friendica core or should we integrate the
> directory into the current core?

*chuckles* I see a wave developing. The dir project was separated to have a less complicate structure then the friendica project IIRC

**Comment by MrPetovan** [comment]
There are two separate concepts in Friendica. The whole library we built in [code]src/[/code], and the controllers and cronjobs we currently have in [code]mod/[/code]. We usually call the library the Framework.

The directory doesn't need Friendica controllers but it can leverage Friendica framework, like all the classes in Util for example. Those classes could be in a separate repository that could be included as a dependency by both project. And when we update a Util class, both projects can use the updated version.

We don't need it because both projects work right now, and there isn't any new external need for it. We don't need it as well because there are multiple frameworks around who do the same stuff generally more elegantly, and we probably don't need to publish yet another framework that started as a specific project.

So we don't "need" it per se, but it would be a fun exercise at least for me. The drawback is that the shared library version has to be managed with regard to backward compatibility whereas we don't care about it when it's only used by Friendica.

**Comment by annando** [comment]
I just realized that this file ```dfrndir.sql``` is the update script as well. So I guess it would be correct to keep the old structure at the top and to add some "alter" command to change the field name.

**Comment by MrPetovan** [comment]
There's no current update mechanism for the Friendica directory and I don't necessarily intend on maintaining one, so I personally won't change the `dfrndir.sql` file according to your feedback.

**Comment by annando** [comment]
Okay. There aren't many directory installations in the wild. But these installations will fail after pulling this code when they don't apply the database changes manually.

We need something for the update. Either a script or documentation or a mixture of both.

**Comment by MrPetovan** [comment]
Merging as people are trying to set up their own directory and it puts them at odds with `dir.friendica.social`.

**Pull request merged**
