### PR TITLE
Upgrade database to utf8mb4

### PR DESCRIPTION
**Pull request by MrPetovan**
EMOJIS!

### CODE REVIEW

**Comment by tobiasd** [comment]
Really, what for? Look at all the work humanity has to decipher ancient emojis.

**Comment by tobiasd** [comment]
> Look at the magnificent user name of the LIBRANET admin!

Yes, exactly what I say. There is a name and then there is a unrecognisable something. Could be an apple maybe, black and white in thin stencil drawing. It is probably something different. I may see something different in a different browser, so I cannot even be sure everyone sees the same hieroglyph that we are supposed to see.

**Comment by MrPetovan** [comment]
It doesn't really matter, they didn't intend on showing a question mark either, so we might as well enable the display that was closer to their initial intent.

**Comment by tobiasd** [comment]
> It doesn't really matter, they didn't intend on showing a question
> mark either

I have to agree here. I guess it is one indicator of getting old, that I don't understand 99.9% all the hieroglyphs, but identify the *good old* ascii art emojis.

**Comment by MrPetovan** [comment]
By the way, it's a rabbit face, Opa. =p

**Comment by annando** [comment]
I see a problem: You compacted the file ```dfrndir.sql```. I guess these update command had been there to sequentially update the database to the current structure. Because you compacted it to just a "if the table does not exist" thing, every current directory installation won't get updated at all. Or miss I something?

**Comment by MrPetovan** [comment]
It isn't meant as an incremental update file, and it is one of the two different phpMyAdmin export outputs. I initially did an export without the `IF NOT EXISTS` option and it put the indices at the end like the original file. When I added the options the indices got grouped in the table description.

In any case this SQL script is an initialization script when someone first set up a directory.

**Comment by MrPetovan** [comment]
Merging as people are trying to set up their own directory and it puts them at odds with `dir.friendica.social`.

**Pull request merged**
