### PR TITLE
Fix missing $db when session write on exit

### PR DESCRIPTION
**Pull request by Hypolite**
This PR fixes the case where `exit;` was called before `session_write_close()`. The DB was already unloaded, and the session handler tried to write the session data to the DB.

Using `killme()` instead avoid this pitfall.

### CODE REVIEW

**Comment by annando** [comment]
Wouldn't it be better to have a ```_destruct()``` function where the database connection is closed? (Like we do in the core?)

**Comment by Hypolite** [comment]
It's already done this way: https://github.com/friendica/dir/blob/master/include/dba.php#L99

However, when simply exiting, the DB object is destroyed before the session handler function are called, which prevents the session to be written. The `killme()` function ensures that the session is written before the Database object is destroyed.

**Comment by Hypolite** [comment]
@annando Can you merge this or do you have further comments?

**Comment by annando** [comment]
Sorry, I had forgotten about this.

**Pull request merged**
