### PR TITLE
Cleanups of "use" and "new" statements

### PR DESCRIPTION
**Pull request by Quix0r**
Some cleanups:
- "use" should be executed before any other line (except strict mode line)
- "import" App class before use it
- sure braces with "new" operator as this invokes the constructor
- set CHMOD 777 for Shell script

### CODE REVIEW

**Comment by MrPetovan** [comment]
Please change the base branch of this PR to `develop` instead of `master` currently.

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
Oooh, it's the dir repo! Then in this case it is deprecated and will be archived at some point in the future. Thanks for your contribution though!

**Comment by Quix0r** [comment]
I have cloned the new repository and will switch to it soon. Thank you for merging it anyway.

**Comment by Quix0r** [comment]
In `friendica-directory` I have found no `develop` branch, too. Just to mention it. :-)

**Comment by MrPetovan** [comment]
Of course, I had no reason no to merge it, since it isn't archived yet. The official Friendica directory still runs on this codebase, because the new one doesn't completely cover the existing API.

**Pull request merged**
